# Generated by Django 3.1.3 on 2021-02-02 15:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=150)),
                ('tag_title', models.CharField(default='Sale', max_length=150)),
                ('tag_title_color', models.CharField(default='orange', max_length=150)),
                ('section', models.CharField(default='section_one', max_length=150)),
                ('category', models.CharField(default='living_room', max_length=150)),
                ('image_1', models.FileField(blank=True, upload_to='product/image_1/')),
                ('image_2', models.FileField(blank=True, upload_to='product/image_2/')),
                ('image_3', models.FileField(blank=True, upload_to='product/image_3/')),
                ('image_4', models.FileField(blank=True, upload_to='product/image_4/')),
                ('image_5', models.FileField(blank=True, upload_to='product/image_5/')),
                ('image_6', models.FileField(blank=True, upload_to='product/image_6/')),
                ('video_link', models.CharField(default='none', max_length=150)),
                ('pdf_link', models.CharField(default='none', max_length=150)),
                ('description', models.TextField(default='none')),
                ('specification', models.TextField(default='none')),
                ('quantity', models.IntegerField(default=1)),
                ('threshold', models.IntegerField(blank=True, default=1, null=True)),
                ('price', models.IntegerField(default=1)),
                ('old_price', models.IntegerField(default=1)),
                ('rating', models.IntegerField(blank=True, default='none', null=True)),
                ('shipping_charge', models.FloatField(default=1)),
                ('delivery_info', models.CharField(default='none', max_length=150)),
                ('abia_shipping', models.IntegerField(default=1)),
                ('adamawa_shipping', models.IntegerField(default=1)),
                ('akwaibom_shipping', models.IntegerField(default=1)),
                ('anambra_shipping', models.IntegerField(default=1)),
                ('slug', models.SlugField(default='rayslug', unique=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=150)),
                ('email', models.CharField(default='none', max_length=150)),
                ('review', models.TextField(default='none')),
                ('status', models.CharField(default='pending', max_length=150)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReviewConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('review', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.review')),
            ],
        ),
        migrations.CreateModel(
            name='ProductQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_shipping_charge', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.quantity')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.ManyToManyField(through='product.ProductReviewConnector', to='product.Review'),
        ),
    ]
