# Generated by Django 3.1.3 on 2021-01-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='abia_shipping',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='adamawa_shipping',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='akwaibom_shipping',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='anambra_shipping',
            field=models.IntegerField(default=1),
        ),
    ]
