# Generated by Django 3.1.5 on 2021-02-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='living_room', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='test', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='pdf_link',
            field=models.CharField(default='none', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(blank=True, default='none', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_link',
            field=models.CharField(default='none', max_length=150),
        ),
    ]
