# Generated by Django 3.1.3 on 2021-01-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='delivery_state',
            field=models.CharField(default='nowhere', max_length=500),
        ),
    ]
