# Generated by Django 3.1.5 on 2021-01-19 09:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_user', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_note', models.TextField(default='Nothing')),
                ('status', models.CharField(default='Pending', max_length=150)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser')),
                ('cart', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
        ),
    ]
